# Sidebar
SIDEBAR_WIDTH = 200
SIDEBAR_SPACING = 36
SIDEBAR_MARGIN_X = 24
SIDEBAR_MARGIN_Y = 32

# Sidebar Logo
SIDEBAR_LOGO_WIDTH = 170
SIDEBAR_LOGO_HEIGHT = 40

# Sidebar Buttons Container
SIDEBAR_BUTTONS_CONTAINER_SPACING = 4
